### ISSUE TITLE
Add Travis stuff 

### ISSUE THREAD

**Issue by davidtedfordholt** [davidtedfordholt/fable.bsts#10]
It seems like I should use this. And probably other tools for checking package builds and coverage and whatnot.

**Comment by mitchelloharawild** [comment]
Worth looking into GitHub Actions via https://github.com/r-lib/actions instead of Travis.
Up to personal preference of course, but I've found it nicer to work with and many R packages are beginning to use it.
If you would like help with this, let me know.

**Comment by davidtedfordholt** [comment]
I'll learn about them over the weekend. Anything that's nicer to work with is my personal preference.

**Comment by davidtedfordholt** [comment]
Added basic CI action. For now, this seems enough.
