### ISSUE TITLE
Install failure :package or namespace load failed for ‘future’

### ISSUE THREAD

**Issue by deorcost** [davidtedfordholt/fable.bsts#17]
Package installation of `fable.bsts` fails with the message:

```
Error : package or namespace load failed for ‘future’:
 .onLoad failed in loadNamespace() for 'globals', details:
  call: asNamespace(ns, base.OK = FALSE)
  error: not a namespace
Error: unable to load R code in package ‘fable.bsts’
Execution halted
```

The package `future` exists on my system and is up to date. It was successfully installed via `install.packages`. 

My system:

*  R version: 4.0.0
*  Platform: macOS 10.15.4 (Catalina)

**Comment by lejarx** [comment]
Same problem 

System
R version 4.0.0
Platform: RHEL 7.6

**Comment by davidtedfordholt** [comment]
@deorcost , I'm sorry it took me so long to even look at this. COVID is a heck of a thing. It's installing for us, and I totally understand that your need for it might have gone by the wayside, but please do let us know if it still won't install for you.
